"""One-shot script: run discovery for 4 topics and save results to YAML."""
import asyncio
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

from nexus.config.models import ModelsConfig
from nexus.llm.client import LLMClient
from nexus.engine.sources.discovery import discover_sources

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
OUT_PATH = DATA_DIR / "sources" / "discovered_sources.yaml"

TOPICS = [
    {
        "name": "Beauty Industry",
        "subtopics": ["skincare trends", "cosmetics regulation", "K-beauty", "clean beauty"],
    },
    {
        "name": "Fashion Industry",
        "subtopics": ["luxury brands", "sustainable fashion", "fashion week", "fast fashion labor"],
    },
    {
        "name": "International Rugby Union",
        "subtopics": ["Six Nations", "Rugby World Cup", "Super Rugby", "World Rugby rankings"],
    },
    {
        "name": "Rwanda News & Politics",
        "subtopics": ["Kagame government", "DRC conflict", "East African Community", "Rwandan economy"],
    },
]


async def main():
    key = os.getenv("GEMINI_API_KEY", "")
    if not key:
        print("GEMINI_API_KEY not set")
        sys.exit(1)

    llm = LLMClient(models_config=ModelsConfig(discovery="gemini-3-flash-preview"), api_key=key)

    all_sections: list[str] = []
    all_sections.append("# Auto-discovered sources — generated by capture_discoveries.py")
    all_sections.append(f"# Model: gemini-3-flash-preview")
    all_sections.append(f"# Date: 2026-03-17")
    all_sections.append("#")
    all_sections.append("# Review before adding to global_registry.yaml or topic source lists.")
    all_sections.append("# Fields: id, name, url, language, tier, affiliation, country, origin")
    all_sections.append("")

    for topic in TOPICS:
        print(f"\n{'='*60}")
        print(f"Discovering: {topic['name']}")
        print(f"{'='*60}")

        result = await discover_sources(
            llm=llm,
            topic_name=topic["name"],
            subtopics=topic["subtopics"],
            existing_urls=set(),
            max_feeds=25,
            data_dir=DATA_DIR,
        )

        all_sections.append(f"# {'='*60}")
        all_sections.append(f"# {topic['name'].upper()}")
        all_sections.append(f"# Subtopics: {', '.join(topic['subtopics'])}")
        all_sections.append(f"# Total: {len(result.feeds)}  (registry: {result.sources_from_registry}, "
                           f"google: {result.sources_from_google_news}, web: {result.sources_from_web})")
        all_sections.append(f"# Diversity — geo: {result.diversity.geographic_score:.2f}  "
                           f"affil: {result.diversity.affiliation_score:.2f}  "
                           f"lang: {result.diversity.language_score:.2f}  "
                           f"overall: {result.diversity.overall:.2f}")
        if result.diversity.warnings:
            for w in result.diversity.warnings:
                all_sections.append(f"#   ⚠ {w}")
        all_sections.append(f"# {'='*60}")
        all_sections.append("")
        all_sections.append(f"{_slug(topic['name'])}:")

        for f in result.feeds:
            origin = _origin(f, result)
            all_sections.append(f"  - id: {f['id']}")
            all_sections.append(f"    name: \"{f.get('name', '?')}\"")
            all_sections.append(f"    url: \"{f['url']}\"")
            all_sections.append(f"    language: {f.get('language', 'en')}")
            all_sections.append(f"    tier: {f.get('tier', 'B')}")
            all_sections.append(f"    affiliation: {f.get('affiliation', 'unknown')}")
            all_sections.append(f"    country: {f.get('country', 'unknown')}")
            all_sections.append(f"    origin: {origin}")
            if f.get("tags"):
                tags_str = ", ".join(f["tags"])
                all_sections.append(f"    tags: [{tags_str}]")
            all_sections.append("")

        print(f"  → {len(result.feeds)} feeds saved")

    OUT_PATH.write_text("\n".join(all_sections))
    print(f"\nWritten to {OUT_PATH}")


def _slug(name: str) -> str:
    return name.lower().replace(" ", "_").replace("&", "and")


def _origin(feed: dict, result) -> str:
    if feed.get("tags"):  # registry sources have tags
        return "registry"
    if "google.com/rss" in feed.get("url", "") or "news.google.com" in feed.get("url", ""):
        return "google_news"
    return "web_discovery"


if __name__ == "__main__":
    asyncio.run(main())
